global using FashionStore.API.Features.Auth.Shared;
global using FashionStore.API.Features.Brands.Shared;
global using FashionStore.API.Features.Categories.Shared;
global using FashionStore.API.Features.MainCarousels.Shared;
global using FashionStore.API.Features.Products.Shared;
global using FashionStore.API.Features.PromotionBanners.Shared;
global using FashionStore.API.Features.PromotionVideos.Shared;
global using FashionStore.API.Features.Users.Shared;
global using FashionStore.API.Features.Auth.ConfirmEmail;
global using FashionStore.API.Features.Auth.ForgotPassword;
global using FashionStore.API.Features.Auth.Login;
global using FashionStore.API.Features.Auth.Register;
global using FashionStore.API.Features.Auth.ResendConfirmationLink;
global using FashionStore.API.Features.Auth.ResetPassword;
global using FashionStore.API.Features.Brands.CreateBrand;
global using FashionStore.API.Features.Categories.CreateCategory;
global using FashionStore.API.Features.Categories.UpdateCategory;
global using FashionStore.API.Features.Users.CreateUser;
global using FashionStore.API.Features.Users.UpdateUser;
global using FashionStore.API.Features.Colors.CreateColor;
global using FashionStore.API.Features.Sizes.CreateSize;
global using FashionStore.API.Features.MainCarousels.CreateMainCarousel;
global using FashionStore.API.Features.MainCarousels.UpdateMainCarousel;
global using FashionStore.API.Features.Products.CreateProduct;
global using FashionStore.API.Features.Products.GetProducts;
global using FashionStore.API.Features.Products.GetStorefront;
global using FashionStore.API.Features.Products.UpdateProduct;
global using FashionStore.API.Features.PromotionBanners.CreatePromotionBanner;
global using FashionStore.API.Features.PromotionBanners.UpdatePromotionBanner;
global using FashionStore.API.Features.PromotionVideos.CreatePromotionVideo;
global using FashionStore.API.Features.PromotionVideos.GetPromotionVideos;
global using FashionStore.API.Features.PromotionVideos.UpdatePromotionVideo;
global using FashionStore.Shared.Common;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using FashionStore.Domain.Abstractions.Auth;
global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using FashionStore.API.Controllers;
global using FashionStore.Domain.Entities;
global using FashionStore.Domain.Enums;
global using FashionStore.Domain.Abstractions.Notification;
global using Microsoft.AspNetCore.Identity;
global using Microsoft.Extensions.Logging;
global using FashionStore.Shared.Constants;




