FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS base
USER root
RUN sed -i 's|http://archive.ubuntu.com|https://archive.ubuntu.com|g; s|http://security.ubuntu.com|https://security.ubuntu.com|g' \
      /etc/apt/sources.list.d/ubuntu.sources \
    && apt-get update \
    && apt-get install -y --no-install-recommends libgssapi-krb5-2 libkrb5-dev \
    && rm -rf /var/lib/apt/lists/*
USER $APP_UID
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["NuGet.Config", "."]
COPY ["FashionStore.API/FashionStore.API.csproj", "FashionStore.API/"]
COPY ["FashionStore.Infrastructure/FashionStore.Infrastructure.csproj", "FashionStore.Infrastructure/"]
COPY ["FashionStore.Domain/FashionStore.Domain.csproj", "FashionStore.Domain/"]
COPY ["FashionStore.Shared/FashionStore.Shared.csproj", "FashionStore.Shared/"]
RUN dotnet restore "./FashionStore.API/FashionStore.API.csproj"
COPY . .
WORKDIR "/src/FashionStore.API"
RUN dotnet publish "./FashionStore.API.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["sh", "-c", "dotnet FashionStore.API.dll --urls http://0.0.0.0:${PORT:-80}"]
